### ISSUE TITLE
Error banner causes confusion

### ISSUE THREAD

**Issue by simensrostad** [hello-nrfcloud/web#793] opened 2024-09-26 14:41 UTC
The banner saying that there is problems detected with your device is shown even if the device is working the way it should.
Its also usually the first thing the user sees when entering the web page.

Proposed change from is to show an indicator that says online/offline.

**Comment by coderbyheart** [comment] 2024-09-26 19:35
Here is an example of a device that is not connected: 
![image](https://github.com/user-attachments/assets/6e562a35-0696-4ecb-92a7-b7f7d141a155)

The error banner is intentional because the device is not working as intended. That is the whole point of the OOB experience.

> The banner saying that there is problems detected with your device is shown even if the device is working the way it should.

In that case the banner is not shown.

Unless further details are provided about the nature of the confusion I am closing this.

**Closed as completed by coderbyheart** 2024-09-26 19:35 UTC
Labels: invalid
