### ISSUE TITLE
Missing UI for GNSS search pattern

### ISSUE THREAD

**Issue by simensrostad** [hello-nrfcloud/web#687] opened 2024-08-07 08:49 UTC
![image](https://github.com/user-attachments/assets/d9c1006e-2d03-42ee-bfcb-fb7baf5eed57)

The firmware now shows green blinking when its searching for GNSS

**Comment by coderbyheart** [comment] 2024-08-07 22:41
Duplicate of #680

**Closed as completed by coderbyheart** 2024-08-07 22:41 UTC
